services:
  backend:
    build:
      context: backend
    env_file:
      - backend/.env
    command: npm run compose:start
    ports:
      - '3001:3001'
    volumes:
      - './backend/src:/run/src'
      - 'hkn-backend-modules:/app/node_modules'

  frontend:
    build:
      context: frontend
    env_file:
      - frontend/.env
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - './frontend/src:/app/src'
      - 'hkn-frontend-modules:/app/node_modules'

  db:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
volumes:
  hkn-frontend-modules:
  hkn-backend-modules:
