/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliateGetRSVPResponse
 */
export interface AffiliateGetRSVPResponse {
    /**
     * 
     * @type {number}
     * @memberof AffiliateGetRSVPResponse
     */
    eventId: number;
    /**
     * 
     * @type {number}
     * @memberof AffiliateGetRSVPResponse
     */
    appUserId: number;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliateGetRSVPResponse
     */
    isRsvped: boolean;
}

export function AffiliateGetRSVPResponseFromJSON(json: any): AffiliateGetRSVPResponse {
    return AffiliateGetRSVPResponseFromJSONTyped(json, false);
}

export function AffiliateGetRSVPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliateGetRSVPResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': json['eventId'],
        'appUserId': json['appUserId'],
        'isRsvped': json['isRsvped'],
    };
}

export function AffiliateGetRSVPResponseToJSON(value?: AffiliateGetRSVPResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventId': value.eventId,
        'appUserId': value.appUserId,
        'isRsvped': value.isRsvped,
    };
}


