/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliateAttendanceResponse
 */
export interface AffiliateAttendanceResponse {
    /**
     * 
     * @type {number}
     * @memberof AffiliateAttendanceResponse
     */
    attendeeId: number;
    /**
     * 
     * @type {number}
     * @memberof AffiliateAttendanceResponse
     */
    eventId: number;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliateAttendanceResponse
     */
    isSignedIn: boolean;
}

export function AffiliateAttendanceResponseFromJSON(json: any): AffiliateAttendanceResponse {
    return AffiliateAttendanceResponseFromJSONTyped(json, false);
}

export function AffiliateAttendanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliateAttendanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attendeeId': json['attendeeId'],
        'eventId': json['eventId'],
        'isSignedIn': json['isSignedIn'],
    };
}

export function AffiliateAttendanceResponseToJSON(value?: AffiliateAttendanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attendeeId': value.attendeeId,
        'eventId': value.eventId,
        'isSignedIn': value.isSignedIn,
    };
}


