/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppUserPostRequest
 */
export interface AppUserPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    major?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    graduationYear?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    inductionClassQuarter?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    role?: AppUserPostRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    preferredName?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    pronoun?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    customPronoun?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserPostRequest
     */
    infoSession?: string;
}

export function AppUserPostRequestFromJSON(json: any): AppUserPostRequest {
    return AppUserPostRequestFromJSONTyped(json, false);
}

export function AppUserPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'major': !exists(json, 'major') ? undefined : json['major'],
        'graduationYear': !exists(json, 'graduationYear') ? undefined : json['graduationYear'],
        'inductionClassQuarter': !exists(json, 'inductionClassQuarter') ? undefined : json['inductionClassQuarter'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'preferredName': !exists(json, 'preferredName') ? undefined : json['preferredName'],
        'pronoun': !exists(json, 'pronoun') ? undefined : json['pronoun'],
        'customPronoun': !exists(json, 'customPronoun') ? undefined : json['customPronoun'],
        'infoSession': !exists(json, 'infoSession') ? undefined : json['infoSession'],
    };
}

export function AppUserPostRequestToJSON(value?: AppUserPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'major': value.major,
        'graduationYear': value.graduationYear,
        'inductionClassQuarter': value.inductionClassQuarter,
        'role': value.role,
        'preferredName': value.preferredName,
        'pronoun': value.pronoun,
        'customPronoun': value.customPronoun,
        'infoSession': value.infoSession,
    };
}

/**
* @export
* @enum {string}
*/
export enum AppUserPostRequestRoleEnum {
    Admin = 'admin',
    Officer = 'officer',
    Member = 'member',
    Inductee = 'inductee',
    Guest = 'guest'
}


