/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceResultResponse
 */
export interface AttendanceResultResponse {
    /**
     * 
     * @type {number}
     * @memberof AttendanceResultResponse
     */
    attendeeId: number;
    /**
     * 
     * @type {number}
     * @memberof AttendanceResultResponse
     */
    eventId: number;
    /**
     * 
     * @type {boolean}
     * @memberof AttendanceResultResponse
     */
    signin: boolean;
}

export function AttendanceResultResponseFromJSON(json: any): AttendanceResultResponse {
    return AttendanceResultResponseFromJSONTyped(json, false);
}

export function AttendanceResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceResultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attendeeId': json['attendeeId'],
        'eventId': json['eventId'],
        'signin': json['signin'],
    };
}

export function AttendanceResultResponseToJSON(value?: AttendanceResultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attendeeId': value.attendeeId,
        'eventId': value.eventId,
        'signin': value.signin,
    };
}


