/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AttendanceRequest
 */
export interface AttendanceRequest {
  /**
   *
   * @type {string}
   * @memberof AttendanceRequest
   */
  startTime: string;
  /**
   *
   * @type {string}
   * @memberof AttendanceRequest
   */
  endTime: string;
}

export function AttendanceRequestFromJSON(json: any): AttendanceRequest {
  return AttendanceRequestFromJSONTyped(json, false);
}

export function AttendanceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttendanceRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    startTime: json['startTime'],
    endTime: json['endTime'],
  };
}

export function AttendanceRequestToJSON(value?: AttendanceRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    startTime: value.startTime,
    endTime: value.endTime,
  };
}
