/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetAttendanceQuery
 */
export interface GetAttendanceQuery {
  /**
   *
   * @type {number}
   * @memberof GetAttendanceQuery
   */
  attendeeId: number;
  /**
   *
   * @type {number}
   * @memberof GetAttendanceQuery
   */
  eventId: number;
}

export function GetAttendanceQueryFromJSON(json: any): GetAttendanceQuery {
  return GetAttendanceQueryFromJSONTyped(json, false);
}

export function GetAttendanceQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetAttendanceQuery {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    attendeeId: json['attendeeId'],
    eventId: json['eventId'],
  };
}

export function GetAttendanceQueryToJSON(
  value?: GetAttendanceQuery | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    attendeeId: value.attendeeId,
    eventId: value.eventId,
  };
}
