/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRSVPQuery
 */
export interface GetRSVPQuery {
    /**
     * 
     * @type {number}
     * @memberof GetRSVPQuery
     */
    eventId: number;
    /**
     * 
     * @type {number}
     * @memberof GetRSVPQuery
     */
    appUserId: number;
}

export function GetRSVPQueryFromJSON(json: any): GetRSVPQuery {
    return GetRSVPQueryFromJSONTyped(json, false);
}

export function GetRSVPQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRSVPQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': json['eventId'],
        'appUserId': json['appUserId'],
    };
}

export function GetRSVPQueryToJSON(value?: GetRSVPQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventId': value.eventId,
        'appUserId': value.appUserId,
    };
}


