/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InducteeSignupInfo
 */
export interface InducteeSignupInfo {
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    major: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    graduationYear: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    preferredName?: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    pronoun?: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    customPronoun?: string;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    infoSession: string;
    /**
     * 
     * @type {boolean}
     * @memberof InducteeSignupInfo
     */
    courseRequirement: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InducteeSignupInfo
     */
    newsletter: boolean;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    role?: InducteeSignupInfoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof InducteeSignupInfo
     */
    inductionClassQuarter?: string;
}

export function InducteeSignupInfoFromJSON(json: any): InducteeSignupInfo {
    return InducteeSignupInfoFromJSONTyped(json, false);
}

export function InducteeSignupInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InducteeSignupInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'major': json['major'],
        'graduationYear': json['graduationYear'],
        'preferredName': !exists(json, 'preferredName') ? undefined : json['preferredName'],
        'pronoun': !exists(json, 'pronoun') ? undefined : json['pronoun'],
        'customPronoun': !exists(json, 'customPronoun') ? undefined : json['customPronoun'],
        'infoSession': json['infoSession'],
        'courseRequirement': json['courseRequirement'],
        'newsletter': json['newsletter'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'inductionClassQuarter': !exists(json, 'inductionClassQuarter') ? undefined : json['inductionClassQuarter'],
    };
}

export function InducteeSignupInfoToJSON(value?: InducteeSignupInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'major': value.major,
        'graduationYear': value.graduationYear,
        'preferredName': value.preferredName,
        'pronoun': value.pronoun,
        'customPronoun': value.customPronoun,
        'infoSession': value.infoSession,
        'courseRequirement': value.courseRequirement,
        'newsletter': value.newsletter,
        'role': value.role,
        'inductionClassQuarter': value.inductionClassQuarter,
    };
}

/**
* @export
* @enum {string}
*/
export enum InducteeSignupInfoRoleEnum {
    Admin = 'admin',
    Officer = 'officer',
    Member = 'member',
    Inductee = 'inductee',
    Guest = 'guest'
}


