/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InductionClassRequest
 */
export interface InductionClassRequest {
  /**
   *
   * @type {string}
   * @memberof InductionClassRequest
   */
  quarter: string;
  /**
   *
   * @type {string}
   * @memberof InductionClassRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof InductionClassRequest
   */
  startDate: string;
  /**
   *
   * @type {string}
   * @memberof InductionClassRequest
   */
  endDate: string;
  /**
   *
   * @type {Array<string>}
   * @memberof InductionClassRequest
   */
  interviewDates?: Array<string>;
}

export function InductionClassRequestFromJSON(
  json: any
): InductionClassRequest {
  return InductionClassRequestFromJSONTyped(json, false);
}

export function InductionClassRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InductionClassRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    quarter: json['quarter'],
    name: json['name'],
    startDate: json['startDate'],
    endDate: json['endDate'],
    interviewDates: !exists(json, 'interviewDates')
      ? undefined
      : json['interviewDates'],
  };
}

export function InductionClassRequestToJSON(
  value?: InductionClassRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    quarter: value.quarter,
    name: value.name,
    startDate: value.startDate,
    endDate: value.endDate,
    interviewDates: value.interviewDates,
  };
}
