/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultipleInductionClassQuery
 */
export interface MultipleInductionClassQuery {
    /**
     * 
     * @type {number}
     * @memberof MultipleInductionClassQuery
     */
    startYear?: number;
    /**
     * 
     * @type {number}
     * @memberof MultipleInductionClassQuery
     */
    endYear?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MultipleInductionClassQuery
     */
    showAffiliates?: boolean;
}

export function MultipleInductionClassQueryFromJSON(json: any): MultipleInductionClassQuery {
    return MultipleInductionClassQueryFromJSONTyped(json, false);
}

export function MultipleInductionClassQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleInductionClassQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startYear': !exists(json, 'startYear') ? undefined : json['startYear'],
        'endYear': !exists(json, 'endYear') ? undefined : json['endYear'],
        'showAffiliates': !exists(json, 'showAffiliates') ? undefined : json['showAffiliates'],
    };
}

export function MultipleInductionClassQueryToJSON(value?: MultipleInductionClassQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startYear': value.startYear,
        'endYear': value.endYear,
        'showAffiliates': value.showAffiliates,
    };
}


