version: 2.1
jobs:
  run_lint_prettier:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "backend/package.json"}}
      - run: npm install --prefix backend
      - save_cache:
          key: package-cache-{{checksum "backend/package.json"}}
          paths:
            - backend/node_modules
      - run:
          command: |
            npm run --prefix backend lint
            cd backend; npx prettier --check ./src/**/*.ts
  run_build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "backend/package.json"}}
      - run: npm install --prefix backend
      - save_cache:
          key: package-cache-{{checksum "backend/package.json"}}
          paths:
            - backend/node_modules
      - run: npm run --prefix backend build:no-check
  run_test:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "backend/package.json"}}
      - run: npm install --prefix backend
      - save_cache:
          key: package-cache-{{checksum "backend/package.json"}}
          paths:
            - backend/node_modules
      - run: npm run --prefix backend test

workflows:
  lint_and_build:
    jobs:
      - run_lint_prettier
      - run_build
      - run_test
