version: 2.1
orbs:
  node: circleci/node@2.0.2
  cypress: cypress-io/cypress@1.24.0
jobs:
  lint_prettier:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run: 
          command: |
            npm run lint
            npx prettier --check ./src/**/*.js
  test:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run: npm run test
workflows:
  lint_and_test:
    jobs:
      - lint_prettier
      - cypress/run:
          requires:
            - lint_prettier
          executor: cypress/base-12-14-0
          start: npm run start
          wait-on: 'http://localhost:3000'
      - test
