version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  run_lint_prettier:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          command: |
            npm run lint
            npx prettier --check ./src/**/*.ts
  run_build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run: npm run build:no-check
  run_test:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run: npm run test

workflows:
  lint_and_build:
    jobs:
      - run_lint_prettier
      - run_build
      - run_test
